In [47]:
import numpy as np
numpy_array=np.arange(1000000)
python_list=list(range(1000000))

In [48]:
%time numpy_array=numpy_array*numpy_array

CPU times: user 5.5 ms, sys: 7.48 ms, total: 13 ms
Wall time: 11.8 ms


In [49]:
%time python_list=[x*x for x in python_list]

CPU times: user 45.1 ms, sys: 18.3 ms, total: 63.4 ms
Wall time: 64.6 ms


In [102]:
%time for _ in range(10): numpy_array=numpy_array*numpy_array

CPU times: user 14.6 ms, sys: 11.7 ms, total: 26.3 ms
Wall time: 24.5 ms


In [106]:
%time for _ in range(10):[x*x for x in python_list]

CPU times: user 439 ms, sys: 149 ms, total: 588 ms
Wall time: 591 ms


In [ ]:
pip install numpy

In [51]:
lst=[1,14,4,7,11,12,3]
first_array=np.array(lst)

In [52]:
lst

[1, 14, 4, 7, 11, 12, 3]

In [53]:
first_array

array([ 1, 14,  4,  7, 11, 12,  3])

# Numpy Array Basics

In [54]:
import numpy as np
array=np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [56]:
array_2d=np.array([range(5), range(5)])

In [62]:
lst=[1,14,4,7,11,12,3]
first_array=np.array(lst)

lst=[[1,14,4,7,9],[7,8,10,4,8]]
array_2d=np.array(lst)

In [63]:
array_2d

array([[ 1, 14,  4,  7,  9],
       [ 7,  8, 10,  4,  8]])

In [64]:
first_array.ndim

1

In [65]:
array_2d.ndim

2

In [73]:
first_array.shape

(7,)

In [74]:
array_2d.shape

(2, 5)

In [66]:
first_array.size

7

In [67]:
array_2d.size

10

In [69]:
first_array.dtype

dtype('int64')

In [68]:
array_2d.dtype

dtype('int64')

In [75]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [87]:
np.zeros(10).reshape(2,5).T #T stands for transpose

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [79]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.arange(5,12,2).reshape(2,2)

array([[ 5,  7],
       [ 9, 11]])

In [33]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.empty((2,3,2)) 

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
array_2d+1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [61]:
array.shape

(5,)

In [8]:
array_2d.shape

(2, 5)

In [9]:
array.size

5

In [11]:
array_2d.size

10

In [13]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [14]:
array.ndim

1

In [15]:
array_2d.ndim

2

In [17]:
array.dtype

dtype('int64')

In [18]:
array_2d.dtype

dtype('int64')

In [19]:
multidimension=np.array([[10,20,30],[20,30,40]])
#multidimension.ndim
#multidimension.shape,
#multidimension.size,
#multidimension.itemsize
#multidimension.nbytes,
#multidimension.dtype


8

In [88]:
np.identity(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [92]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [93]:
np.arange(0,100,11)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [89]:
lst=["I","love","python"]
array_st=np.array(lst)
print(array_st)

['I' 'love' 'python']


In [90]:
array_st.dtype

dtype('<U6')

# Numpy Array Creation

In [35]:
np.ones((4), dtype='int')

array([1, 1, 1, 1])

In [36]:
np.ones(2)

array([1., 1.])

In [38]:
np.zeros(100,"int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.zeros(100,"int").reshape(5,20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
np.identity(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(5,10,2)

array([5, 7, 9])

In [50]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [51]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [52]:
np.linspace(8,80,10)

array([ 8., 16., 24., 32., 40., 48., 56., 64., 72., 80.])

# Random Number Array

In [95]:
import numpy as np

In [104]:
rng=np.random.default_rng(0)
random_array=rng.random(10).round(2)

In [105]:
random_array

array([0.64, 0.27, 0.04, 0.02, 0.81, 0.91, 0.61, 0.73, 0.54, 0.94])

In [108]:
rng = np.random.default_rng(143)
rints = rng.integers(low=10, high=100, size=10)
rints

array([93, 47, 70, 97, 19, 55, 74, 68, 84, 73])

In [110]:
rng.normal(50,5,10).round(2)

array([54.74, 52.06, 46.31, 51.39, 46.86, 42.84, 59.77, 59.92, 54.23,
       51.69])

In [29]:
rng=np.random.default_rng(12345)
random_array=rng.random(10)

In [ ]:
rng=np.random.default_rng()


In [39]:
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [111]:
rng = np.random.default_rng(143)
rints = rng.integers(low=10, high=100, size=10)
rints
#rng.integers(0,10,10).reshape(5,2)

array([93, 47, 70, 97, 19, 55, 74, 68, 84, 73])

In [11]:
rng.normal(50,5,10) ##normal distribution

array([54.40339244, 42.43280947, 45.84272872, 51.38518668, 54.64502039,
       56.79861244, 53.80756492, 46.86916128, 45.9487413 , 47.22031582])

# Array Indexing & Slicing

In [4]:
###One Dimension Array
integers_array=np.arange(11,23)

In [125]:
product=['fruit','vegetable','cereal','dairy',"eggs","snacks","beverage","coffee","tea","spices"]
products=np.array(product)
product[-1]
product[1]
product[2:6]

['cereal', 'dairy', 'eggs', 'snacks']

In [131]:
products=products.reshape(2,5)

In [132]:
products

array([['fruit', 'vegetable', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverage', 'coffee', 'tea', 'spices']], dtype='<U9')

In [138]:
products[:,1:2]

array([['vegetable'],
       ['beverage']], dtype='<U9')

In [140]:
products[:,2:]

array([['cereal', 'dairy', 'eggs'],
       ['coffee', 'tea', 'spices']], dtype='<U9')

In [141]:
products[1,3]

'tea'

In [31]:
integers_array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [19]:
integers_array[-1]

20

In [71]:
integers_array[:5]

array([11, 12, 13, 14, 15])

In [72]:
integers_array[5:]

array([16, 17, 18, 19, 20, 21, 22])

In [7]:
integers_array[::2] ###skip size

array([11, 13, 15, 17, 19, 21])

In [25]:
integers_array[1::2]

array([12, 14, 16, 18, 20])

In [10]:
integers_array[4:9:2]

array([15, 17, 19])

In [119]:
new_2darray=np.arange(11,23).reshape(3,4)

In [120]:
new_2darray[:,:]

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [121]:
new_2darray[1,2]

17

In [123]:
new_2darray[0:2,0:3]

array([[11, 12, 13],
       [15, 16, 17]])

In [85]:
new_2darray[0:1,0:4]

array([[11, 12, 13, 14]])

In [63]:
new_2darray[0:2,1:2]

array([[12],
       [16]])

In [77]:
new_2darray[1:,1:2]

array([[16],
       [20]])

In [60]:
new_2darray[0:2,1:2]

array([[14]])

In [78]:
new_2darray[1:2,1:3]

array([[16, 17]])

In [80]:
new_2darray[:,2:3]

array([[13],
       [17],
       [21]])

In [80]:
new_2darray[1:,0:]

array([[15, 16, 17, 18],
       [19, 20, 21, 22]])

In [46]:
new_2darray[0,1]

12

In [45]:
new_2darray[0,1:]

array([12, 13, 14])

# Array Arithmetic Operations

In [159]:
rng=np.random.default_rng(243)
inventory=rng.integers(0,100,10)
inventory

array([90, 47, 65, 87, 96, 82, 55, 92, 84, 28])

In [160]:
inventory+2

array([92, 49, 67, 89, 98, 84, 57, 94, 86, 30])

In [161]:
price1=(rng.random(11)*10).round(2)
price=(rng.random(10)*10).round(2)

In [162]:
price1

array([3.28, 4.04, 7.61, 7.37, 7.13, 0.42, 9.3 , 6.92, 9.46, 6.12, 1.86])

In [155]:
inventory*price1 ###imbalance shape of both array

ValueError: operands could not be broadcast together with shapes (10,) (11,) 

In [156]:
inventory*price

array([198.51,  88.14,  15.81, 732.72, 430.56, 370.76, 436.32, 111.3 ,
        45.21, 171.  ])

In [146]:
inventory_list=list(inventory)
new_inventory=[]
for x in inventory_list:
    new_inventory.append(x+2)

    
new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

# Array Filtering Operation

In [163]:
rng=np.random.default_rng(100)
sales_array=rng.integers(100,1000,10)
np_array=np.arange(20)

In [165]:
np_array
#sales_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
np_array[np_array%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
even_odd=np.array(['even',"odd"]*10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [91]:
even_odd[even_odd!="odd"]

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [93]:
np_array[even_odd!="odd"]=0

In [94]:
np_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [96]:
np_array[2]=2

In [97]:
np_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [170]:
np_array=np.arange(20)
np_array[np_array%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [166]:
x=rng.integers(0,100,10).reshape(2,5)
x


array([[94, 59, 41, 79, 92],
       [91,  0, 68, 71, 18]])

In [167]:
x[(x>12) & (x<94)]

array([59, 41, 79, 92, 91, 68, 71, 18])

In [169]:
x[(x<45) | (x==92)]

array([41, 92,  0, 18])

In [130]:
x[mask]

array([22,  9,  6, 85, 27])

In [182]:
inventory=[12,102,18,0,0]
product=['fruit','vegetable','cereal'
              ,'dairy','eggs',"bicuits"]
inventory_array=np.array(inventory)
product_array=np.array(product)

In [183]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [184]:
product_array

array(['fruit', 'vegetable', 'cereal', 'dairy', 'eggs', 'bicuits'],
      dtype='<U9')

In [185]:
product_array[inventory_array==0]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5

In [177]:
product_array[inventory_array>0]

array(['fruit', 'vegetable', 'cereal'], dtype='<U9')

In [133]:
inventory=[12,102,18,0,0]
product=['fruit','vegetable','cereal'
              ,'dairy','eggs']
inventory_array=np.array(inventory)
product_array=np.array(product)
product_array[inventory_array>0]

In [134]:
product_array[inventory_array>0]

array(['fruit', 'vegetable', 'cereal'], dtype='<U9')

# Array Where Operation

In [186]:
inventory=[12,102,18,0,0]
product=['fruit','vegetable','cereal'
              ,'dairy','eggs']
inventory_array=np.array(inventory)
product_array=np.array(product)

In [188]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [187]:
np.where(inventory_array<=0,"out of stock","in stock")

array(['in stock', 'in stock', 'in stock', 'out of stock', 'out of stock'],
      dtype='<U12')

In [190]:
np.where(inventory_array<=0,product_array,"in stock")

array(['in stock', 'in stock', 'in stock', 'dairy', 'eggs'], dtype='<U9')

In [233]:
np.where(inventory_array<=0,print (f"products: {product_array}"), "in stock")

products: ['fruit' 'vegetable' 'cereal' 'dairy' 'eggs']


array(['in stock', 'in stock', 'in stock', None, None], dtype=object)

In [191]:
my_array=np.arange(20)

In [192]:
np.where((my_array%2==0) | (),"even","odd")

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [193]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [215]:
sales_array=rng.integers(0,100,10).reshape(2,5)
sales_array

array([[22, 99, 43, 97, 88],
       [39, 44, 32, 80, 86]])

In [216]:
sales_array.sort(axis=1)

In [217]:
sales_array

array([[22, 43, 88, 97, 99],
       [32, 39, 44, 80, 86]])

In [218]:
sales_array1=rng.integers(0,100,10).reshape(2,5)
sales_array1

array([[48, 79, 96, 69, 70],
       [40, 96, 38, 64, 13]])

In [219]:
sales_array1.sort(axis=0)

In [220]:
sales_array1

array([[40, 79, 38, 64, 13],
       [48, 96, 96, 69, 70]])

In [221]:
sales_array2=rng.integers(0,100,10).reshape(2,5)
sales_array2

array([[63, 62, 17,  8, 82],
       [27, 84, 65, 11,  1]])

In [228]:
sales_array2.sort(axis=0)

In [229]:
sales_array2

array([[ 1, 11, 27, 63, 82],
       [ 8, 17, 62, 65, 84]])

In [230]:
sales_array2

array([[ 1, 11, 27, 63, 82],
       [ 8, 17, 62, 65, 84]])

In [121]:
np.where(my_array%2==0,"even",np.where(my_array==9,my_array,"odd"))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

# Array Aggregation Methods

In [32]:
sales_array=rng.integers(0,100,10).reshape(2,5)

In [33]:
sales_array=sales_array.reshape(2,5)

In [34]:
sales_array.sum()

613

In [35]:
sales_array.mean()

61.3

In [36]:
sales_array.max()

94

In [37]:
sales_array.min()

0

In [38]:
sales_array.sum(axis=0) ##aggregaters across rows

array([185,  59, 109, 150, 110])

In [39]:
sales_array.sum(axis=1) ###aggregates across columns

array([365, 248])

In [40]:
np.median(sales_array)

69.5

In [41]:
np.mean(sales_array)

61.3

In [42]:
np.percentile(sales_array,90)

92.2

In [43]:
np.sqrt(sales_array)

array([[9.69535971, 7.68114575, 6.40312424, 8.88819442, 9.59166305],
       [9.53939201, 0.        , 8.24621125, 8.42614977, 4.24264069]])

In [44]:
sales_array.sort(axis=0)

In [115]:
sales_array

array([[36, 41, 80, 85, 89],
       [37, 41, 73, 87, 90]])

In [112]:
sales_array

array([[36, 89, 41, 80, 85],
       [90, 73, 37, 87, 41]])

In [117]:
sales_array

array([[36, 41, 73, 85, 89],
       [37, 41, 80, 87, 90]])

In [62]:
print(one_d_array)

[10 20 30 40 50]


In [63]:
type(one_d_array)

numpy.ndarray

In [64]:
type(lst)

list

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
np.ones((4,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
np.zeros(12).reshape(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.empty((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [75]:
multidimension=np.array([[10,20,30],[20,30,40]])
print(multidimension)

[[10 20 30]
 [20 30 40]]


In [73]:
multidimension.ndim ###dimension

2

In [74]:
multidimension.shape

(2, 3)

In [76]:
multidimension.size

6

In [78]:
multidimension.dtype

dtype('int64')

In [79]:
multidimension.nbytes

48

In [92]:
np.arange(111,1113,10)

array([ 111,  121,  131,  141,  151,  161,  171,  181,  191,  201,  211,
        221,  231,  241,  251,  261,  271,  281,  291,  301,  311,  321,
        331,  341,  351,  361,  371,  381,  391,  401,  411,  421,  431,
        441,  451,  461,  471,  481,  491,  501,  511,  521,  531,  541,
        551,  561,  571,  581,  591,  601,  611,  621,  631,  641,  651,
        661,  671,  681,  691,  701,  711,  721,  731,  741,  751,  761,
        771,  781,  791,  801,  811,  821,  831,  841,  851,  861,  871,
        881,  891,  901,  911,  921,  931,  941,  951,  961,  971,  981,
        991, 1001, 1011, 1021, 1031, 1041, 1051, 1061, 1071, 1081, 1091,
       1101, 1111])

In [93]:
np.linspace(11,1113,10)

array([  11.        ,  133.44444444,  255.88888889,  378.33333333,
        500.77777778,  623.22222222,  745.66666667,  868.11111111,
        990.55555556, 1113.        ])

In [111]:
rng=np.random.default_rng(42)


In [106]:
rng.random(10) 


array([0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394,
       0.33966929, 0.062511  , 0.35706816, 0.20250319, 0.4305179 ])

In [112]:
rng.integers(0, 100,10)


array([ 8, 77, 65, 43, 43, 85,  8, 69, 20,  9])

In [107]:
rng.normal(10,5,7)


array([17.86374339,  7.26107561,  8.54153216, 13.60574701,  9.20798481,
        8.8109699 , 12.48272073])

In [8]:
a=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])

b=np.array([3, 4, 8])
c=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])
d=a*b
e=a*c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# IF ELSE STATEMENT
# WHILE LOOP
# FOR LOOP 
# LIST COMPREHENSION
# ANY ONE FUCNTION 
# ALL PYTHON BUILT IN DATA TYPES 

In [16]:
import numpy as np

In [26]:
rng=np.random.default_rng(42)


In [29]:
array_2d=rng.integers(11,23,10).reshape(5,2)


In [32]:
array_1d=rng.integers(11,23,10)

In [33]:
print(array_2d)

[[17 15]
 [13 22]
 [20 18]
 [15 20]
 [17 16]]


In [34]:
print(array_1d)

[20 19 15 11 22 16 21 19 20 20]


In [48]:
product_list=['fruit','vegetable','cereal','dairy',"eggs","snacks","beverage","coffee","tea","spices"]

In [49]:
product_array=np.array(products)

In [46]:
product_array[1]

'vegetable'

In [51]:
product_list[1]

'vegetable'

In [52]:
product_list[5:]

['snacks', 'beverage', 'coffee', 'tea', 'spices']

In [54]:
product_array[5:]

array(['snacks', 'beverage', 'coffee', 'tea', 'spices'], dtype='<U9')

In [55]:
new_2darray=np.arange(11,23).reshape(3,4)


In [56]:
new_2darray

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [59]:
new_2darray[0:,0:1]

array([[11],
       [15],
       [19]])

In [65]:
new_2darray[0:1,0:2]

array([[11, 12]])

In [64]:
new_2darray[0:3,0:2]

array([[11, 12],
       [15, 16],
       [19, 20]])

In [66]:
new_2darray[1,1]

16

In [148]:
rng=np.random.default_rng(42)
inventory=rng.integers(0,100,10)

In [90]:
price=(rng.random(10)*10).round(2)
new_price=(rng.random(11)*10).round(2)

In [84]:
inventory

array([ 8, 77, 65, 43, 43, 85,  8, 69, 20,  9])

In [89]:
inventory*10*price

array([ 181.6, 4273.5,  416. , 3560.4, 2717.6, 6443. ,  284. , 6699.9,
       1786. ,  700.2])

In [149]:
inventory*10

array([ 80, 770, 650, 430, 430, 850,  80, 690, 200,  90])

In [92]:
new_price

array([1.89, 1.3 , 4.76, 2.27, 6.7 , 4.37, 8.33, 7.  , 3.12, 8.32, 8.05])

In [93]:
price

array([1.95, 4.67, 0.44, 1.54, 6.83, 7.45, 9.68, 3.26, 3.7 , 4.7 ])

In [153]:
a=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])

b=np.array([3, 4, 8])
c=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])
d=a*b
e=a*c


In [152]:
d

array([[ 3,  8, 24],
       [12, 20, 48],
       [21, 32, 72],
       [30, 44, 96]])

In [154]:
e

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [96]:
np_array=np.arange(20)
print(np_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [95]:
np_array[np_array%2==0]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [97]:
x=rng.integers(0,100,10)


In [98]:
x

array([84, 38, 89, 28, 23, 68, 63, 13, 83, 19])

In [100]:
x[(x>23) & (x<89)]

array([84, 38, 28, 68, 63, 83])

In [102]:
inventory=[12,102,18,0,0]
product=['fruit','vegetable','cereal'
              ,'dairy','eggs']
inventory_array=np.array(inventory)
product_array=np.array(product)



In [104]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [105]:
product_array

array(['fruit', 'vegetable', 'cereal', 'dairy', 'eggs'], dtype='<U9')

In [103]:
product_array[inventory_array>0]

array(['fruit', 'vegetable', 'cereal'], dtype='<U9')

In [111]:
np.where(inventory_array<=0,"Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [113]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [114]:
product_array

array(['fruit', 'vegetable', 'cereal', 'dairy', 'eggs'], dtype='<U9')

In [115]:
np.where(inventory_array<=0,"Out of Stock",np.where(inventory_array>=102, "too many stock", "perfectly stock"))

array(['perfectly stock', 'too many stock', 'perfectly stock',
       'Out of Stock', 'Out of Stock'], dtype='<U15')

In [116]:
sales_array=rng.integers(0,100,10).reshape(2,5)


In [120]:
sales_array

array([[80,  0, 79, 78, 78],
       [66, 47, 70, 27, 78]])

In [125]:
sales_array.sum()

603

In [121]:
sales_array.mean()

60.3

In [122]:
sales_array.max()

80

In [123]:
sales_array.min()

0

In [133]:
sales_array=rng.integers(0,100,10).reshape(2,5)

In [127]:
sales_array.sum(axis=1)

array([315, 288])

In [128]:
sales_array.sum(axis=0)

array([146,  47, 149, 105, 156])

In [129]:
sales_array

array([[80,  0, 79, 78, 78],
       [66, 47, 70, 27, 78]])

In [131]:
sales_array.min(axis=1)

array([ 0, 27])

In [132]:
sales_array.min(axis=0)

array([66,  0, 70, 27, 78])

In [134]:
np.sqrt(sales_array)

array([[7.41619849, 6.70820393, 7.07106781, 7.48331477, 1.73205081],
       [3.60555128, 4.89897949, 3.31662479, 6.55743852, 8.1240384 ]])

In [135]:
np.mean(sales_array)

36.6

In [136]:
sales_array

array([[55, 45, 50, 56,  3],
       [13, 24, 11, 43, 66]])

In [137]:
sales_array.sort()

In [138]:
sales_array

array([[ 3, 45, 50, 55, 56],
       [11, 13, 24, 43, 66]])

In [141]:
sales_array.sort(axis=0)

In [140]:
sales_array

array([[ 3, 45, 50, 55, 56],
       [11, 13, 24, 43, 66]])

In [142]:
sales_array

array([[ 3, 13, 24, 43, 56],
       [11, 45, 50, 55, 66]])

In [145]:
lst=[1,2,3,4]
S=np.array([1,2,3,4])
S[0:2]=99
#S[3]=99


In [146]:
S

array([99, 99,  3,  4])